deployment:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  vovastl:
    image:
      repository: vova0911/vovastl
      tag: amd64_1.1.21
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 256Mi
kubernetesClusterDomain: cluster.local
pvc:
  dataPvc:
    storageClass: ""
    storageRequest: 1Gi
service:
  ports:
    - nodePort: 30089
      port: 80
      protocol: TCP
      targetPort: 5000
  type: NodePort
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: vova-g.tplinkdns.com
      paths:
        - path: /vovastl(/|$)(.*)
          pathType: ImplementationSpecific
  tls: []
