spec:
  destination:
    server: https://kubernetes.default.svc

default_values:
  branch: main
  repoURL: https://github.com/V0vaG/helm_test

apps:
  # - name: weather
    # branch: test
    # repoURL: https://github.com/V0vaG/helm_test
  # - name: vpkg
  - name: topix
  #- name: vbank
  - name: jellyfin
  # - name: tools
  #- name: vhub
  #- name: vvolt
  #- name: factory
  - name: vovastl
  #- name: vovarepo
  #- name: weprintcloud
  #- name: postgresql
  #- name: vhide
  - name: vvault
  - name: mongodb
  - name: list
  # - name: kiwix
  # - name: gitlab
  # - name: gitea
  #- name: nextcloud
  #- name: nginx
  # - name: coldvaultmanager
  # - name: artifactory
  - name: minihub
  # - name: vovagpt
  #- name: otacd
  - name: otacd-app
    path: otacd-app
  - name: otacd-db
    path: otacd-db
