apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otacd-db.fullname" . }}-mongodb-deployment
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "otacd-db.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mongodbDeployment.replicas }}
  selector:
    matchLabels:
      app: mongodb
    {{- include "otacd-db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: mongodb
      {{- include "otacd-db.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_DATABASE
          value: {{ quote .Values.mongodbDeployment.mongodb.env.mongoInitdbDatabase }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.mongodbDeployment.mongodb.image.repository }}:{{ .Values.mongodbDeployment.mongodb.image.tag
          | default .Chart.AppVersion }}
        name: mongodb
        ports:
        - containerPort: 27017
        resources: {{- toYaml .Values.mongodbDeployment.mongodb.resources | nindent 10
          }}
        volumeMounts:
        - mountPath: /data/db
          name: mongo-data
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: {{ include "otacd-db.fullname" . }}-otacd-mongo-pvc

