apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otacd-minio.fullname" . }}-minio-deployment
  labels:
  {{- include "otacd-minio.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.minioDeployment.replicas }}
  selector:
    matchLabels:
      app: minio
    {{- include "otacd-minio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: minio
      {{- include "otacd-minio.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: minio
        image: {{ .Values.minioDeployment.minio.image.repository }}:{{ .Values.minioDeployment.minio.image.tag
          | default .Chart.AppVersion }}
        command:
        - /bin/sh
        - -c
        - minio server /data --console-address ":9001"
        env:
        - name: MINIO_ROOT_USER
          value: {{ quote .Values.minioDeployment.minio.env.rootUser }}
        - name: MINIO_ROOT_PASSWORD
          value: {{ quote .Values.minioDeployment.minio.env.rootPassword }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: console
        resources: {{- toYaml .Values.minioDeployment.minio.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /data
          name: minio-data
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: {{ include "otacd-minio.fullname" . }}-minio-data-pvc

