deployment:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  vvault:
    env:
      mongoUrl: mongodb://mongodb-service.argocd.svc.cluster.local:27017
    image:
      repository: 192.168.68.64:5000/vvault
      tag: amd64_0.2.18
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 256Mi
kubernetesClusterDomain: cluster.local
pvc:
  dataPvc:
    storageClass: ""
    storageRequest: 1Gi
service:
  ports:
    - nodePort: 30096
      port: 80
      protocol: TCP
      targetPort: 5000
  type: NodePort
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: vova-g.tplinkdns.com/vvault
      paths:
        - path: (/|$)(.*)
          pathType: ImplementationSpecific
  tls: []
